services:
  db:
    image: postgres:15-alpine
    container_name: phe-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phe
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d phe"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - phe-network

  bot:
    build: .
    container_name: phe-bot
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/phe"
      TIMEZONE: "${TIMEZONE:-Europe/Amsterdam}"
      LOOKBACK_WEEKS: "${LOOKBACK_WEEKS:-12}"
      RUN_COOLDOWN_MIN: "${RUN_COOLDOWN_MIN:-60}"
      ADMIN_IDS: "${ADMIN_IDS}"
      API_PORT: "${API_PORT:-8080}"
      WEBAPP_URL: "${WEBAPP_URL}"
      # Email settings
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
    volumes:
      - uploads:/app/uploads
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - phe-network

networks:
  phe-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  uploads:
    driver: local